# Generated by Django 4.0.5 on 2022-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_information',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Awards/avatars_kuiof2.png', upload_to='Awards'),
        ),
    ]
